### ISSUE TITLE
microrepl hangs my microbit

### ISSUE THREAD

**Issue by rhubarbdog** [ntoll/microrepl#23] opened 2022-12-22 22:22 UTC
when i have a running microbit and use serial terminal `screen /dev/ttyACM0 115200` it joins a running microbit seamlessly.
For some reason when i use `microrepl` it stops the current running program

**Comment by ntoll** [comment] 2022-12-23 13:06
It's designed to work that way (see: https://github.com/ntoll/microrepl/blob/master/microrepl.py#L99).

The whole point of this program is to drop you into the REPL (i.e. the Read Evaluate Print and Loop aspect of MicroPython). That's why it stops whatever is running and gets you to the Python prompt.

Closing because this is expected behaviour. But many thanks for taking the time to report this (others who may wonder, will find this useful exchange via a quick Google). Season's greetings (again). :snowman:

**Closed as completed by ntoll** 2022-12-23 13:06 UTC
