### ISSUE TITLE
microrepl keeps crashing

### ISSUE THREAD

**Issue by rhubarbdog** [ntoll/microrepl#24] opened 2022-12-22 22:55 UTC
from time to time `microrepl` crashes with the following output
```
Exception in thread rx:
Traceback (most recent call last):

EXIT - see you soon... :-)
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stderr>'> at interpreter shutdown, possibly due to daemon threads
Python runtime state: finalizing (tstate=0x10c40c0)

Thread 0x00007f318d32a700 (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 1202 in invoke_excepthook
  File "/usr/lib/python3.8/threading.py", line 934 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007f318db80740 (most recent call first):
<no Python frame>
Aborted (core dumped)
```

is this being caused by me pressing the reset button on the microbit
I get the a similar error if i have `microrepl` running and pull the USB ,lead out

**Comment by ntoll** [comment] 2022-12-23 13:10
@rhubarbdog the error is basically saying that the thread used for receiving data from the device (`Exception in thread rx`), can't get access to a resource it needs (`stderr`). This isn't so much a problem with microrepl, as a problem in Python and how it interacts with the wider operating system.

This doesn't happen for me and so I wonder if there's something unique about your setup, OS, combination of Python version and so on that is causing this.

Closing this since I can't reproduce. Season's greetings (again, again). :santa:

**Closed as completed by ntoll** 2022-12-23 13:10 UTC
