### ISSUE TITLE
Ctrl-C crashes microrepl

### ISSUE THREAD

**Issue by rhubarbdog** [ntoll/microrepl#22] opened 2022-12-22 09:01 UTC
I'm having problems putting a new `main.py` on my microbit with microFS.

`ufs put program.py main.py` crashes unable to enter raw REPL

so i use `microrepl` to reboot and stop the microbit when i press Ctrl-C i get the following output
 
```
Exception in thread rx:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner

EXIT - see you soon... :-)
```

**Comment by ntoll** [comment] 2022-12-23 13:03
@rhubarbdog if `ufs` can't find the raw REPL then MicroPython probably isn't working properly.

As for `CTRL-C`, that's just the standard way to terminate the running program (i.e. in this case `microrepl`).

I'll close this since these problems appear to be misconfiguration and/or expected behaviour. Thanks for reporting though and season's greetings. :christmas_tree:

**Closed as completed by ntoll** 2022-12-23 13:03 UTC
